ktor:
  application:
    name: "ktor-api"
    modules:
      - com.api.ApplicationKt.module
  deployment:
    port: 8000

jwt:
  domain: "https://jwt-provider-domain/"
  audience: "jwt-audience"
  realm: "ktor-api"

storage:
  url: "jdbc:postgresql://localhost:6432/testdb"
  user: "testpguser"
  password: "testpgpass"
  driver: "org.postgresql.Driver"