ktor:
  application:
    modules:
      - ktor.sample.ApplicationKt.module
  deployment:
    port: 8000
postgres:
  url: "jdbc:postgresql://localhost:6432/testdb"
  user: testpguser
  password: testpgpass