spring:
  application:
    name: Kotlin Spring
  datasource:
    url: jdbc:postgresql://localhost:6432/testdb
    username: testpguser
    password: testpgpass
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 16
      auto-commit: false
      connection-timeout: 10000
      idle-timeout: 60000
      minimum-idle: 2
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.format_sql: true
      hibernate.jdbc.lob.non_contextual_creation: true
  liquibase:
    change-log: classpath:liquibase/changelog/changelog.xml
  data:

jwt:
  key: "9a4f2c8d3b7a1e6f45c8a0b3f267d8b1d4e6f3c8a9d2b5f8e3a9c8b5f6v8a3d9"
  access-token-expiration: 3600000
  refresh-token-expiration: 86400000

server:
  port: 8000
